#sudo: required
services:
  - docker

before_install:
  - docker build -t rezacse08/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rezacse08/react-test npm test

after_success:
  - docker build -t rezacse08/multi-client ./client
  - docker build -t rezacse08/multi-nginx ./nginx
  - docker build -t rezacse08/multi-server ./server
  - docker build -t rezacse08/multi-worker ./worker
  #Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images & push them to docker hub
  - docker push rezacse08/multi-client
  - docker push rezacse08/multi-nginx
  - docker push rezacse08/multi-server
  - docker push rezacse08/multi-worker
